// Writes src/tiles.ts from tiles/index.json. Tiles go in palette rotation, each
// palette's tiles in a hashed order, so seeds in a row never share a palette.
// The order is the contract: never reorder or remove a tile, only append.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url);
const { tiles } = JSON.parse(readFileSync(new URL("tiles/index.json", root)));
const PALETTES = [
  "blue",
  "cyan",
  "green",
  "lime",
  "yellow",
  "periwinkle",
  "pink",
];
const hash = (t) => createHash("sha1").update(t.id).digest("hex");
const byPalette = Object.fromEntries(
  PALETTES.map((p) => [
    p,
    tiles
      .filter((t) => t.palette === p)
      .sort((a, b) => (hash(a) < hash(b) ? -1 : 1)),
  ]),
);
const order = [];
for (let i = 0; PALETTES.some((p) => byPalette[p].length); i++) {
  const p = PALETTES[i % PALETTES.length];
  if (byPalette[p].length) order.push(byPalette[p].shift());
}
const moods = [...new Set(order.map((t) => t.mood))].sort();
const palettes = PALETTES.filter((p) => order.some((t) => t.palette === p));
const strings = (xs) => xs.map((x) => `"${x}"`).join(", ");

writeFileSync(
  new URL("src/tiles.ts", root),
  `// Generated by scripts/tiles.mjs from tiles/index.json; do not edit.
export type Mood = ${moods.map((m) => `"${m}"`).join(" | ")};
export type Palette = ${palettes.map((p) => `"${p}"`).join(" | ")};

export interface Tile {
  readonly id: string;
  readonly mood: Mood;
  readonly palette: Palette;
  /** The tile's mean colour, for the box while the image loads. */
  readonly tone: string;
}

export const MOODS: readonly Mood[] = [${strings(moods)}];
export const PALETTES: readonly Palette[] = [${strings(palettes)}];

export const TILES: readonly Tile[] = [
${order.map((t) => `  { id: "${t.id}", mood: "${t.mood}", palette: "${t.palette}", tone: "${t.tone}" },`).join("\n")}
];
`,
);
console.log(`${order.length} tiles`);
